/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.record;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Ankit Ratanker
 */
public class Insert extends javax.swing.JFrame {

     /* Creates new form Insert
     */
    public Insert() {
        initComponents();
        //setSize(1600,1600);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RollNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Num = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Fname = new javax.swing.JLabel();
        Fname1 = new javax.swing.JLabel();
        MName = new javax.swing.JTextField();
        Fname2 = new javax.swing.JLabel();
        LName = new javax.swing.JTextField();
        Fname3 = new javax.swing.JLabel();
        FMName = new javax.swing.JTextField();
        Fname4 = new javax.swing.JLabel();
        FFName = new javax.swing.JTextField();
        Fname5 = new javax.swing.JLabel();
        FLName = new javax.swing.JTextField();
        Fname6 = new javax.swing.JLabel();
        Fname7 = new javax.swing.JLabel();
        Fname8 = new javax.swing.JLabel();
        Date = new javax.swing.JComboBox<>();
        Month = new javax.swing.JComboBox<>();
        Year = new javax.swing.JComboBox<>();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Add Record ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Roll No:*");

        RollNo.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        RollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollNoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("Name:*");

        Email.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("Father's Name:");

        FName.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("Date Of Birth:*");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setText("Email Address:");

        Num.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setText("Contact Number:");

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Fname.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Fname.setText("First Name");

        Fname1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Fname1.setText("Middile Name");

        MName.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        Fname2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Fname2.setText("Last Name");

        LName.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        Fname3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Fname3.setText("First Name");

        FMName.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        Fname4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Fname4.setText("Middile Name");

        FFName.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        Fname5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Fname5.setText("Last Name");

        FLName.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        FLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FLNameActionPerformed(evt);
            }
        });

        Fname6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Fname6.setText("Month");

        Fname7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Fname7.setText("Year");

        Fname8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Fname8.setText("Date");

        Date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Date.setToolTipText("");
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        Month.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "January", "Februray", "March", "Aprail", "May", "June", "July", "August", "September", "October", "November", "December" }));
        Month.setToolTipText("");
        Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthActionPerformed(evt);
            }
        });

        Year.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        Year.setToolTipText("");
        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(Fname3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(Fname4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(Fname5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(184, 184, 184)
                                    .addComponent(jLabel1)
                                    .addGap(21, 21, 21))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(151, 151, 151)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FFName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FMName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(Fname8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85)
                                        .addComponent(Fname6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(Fname7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FLName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(MName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(RollNo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(65, 65, 65)
                                        .addComponent(Fname2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 678, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(408, 408, 408))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RollNo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fname)
                            .addComponent(Fname1)
                            .addComponent(Fname2))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fname3)
                            .addComponent(Fname4)
                            .addComponent(Fname5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(FFName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FMName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FLName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fname8)
                            .addComponent(Fname6)))
                    .addComponent(Fname7))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(60, 60, 60)
                .addComponent(jButton2)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addContainerGap(1263, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdminMenu oj=new AdminMenu();
        oj.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              String roll,n1,n2,n3,f1,f2,f3,dd,mm,yy,email,contact;
              roll=RollNo.getText();
              try{
                  for(int i=0;i<roll.length();i++)
                          {
                              int a = Integer.parseInt(String.valueOf(roll.charAt(i)));
                          }
              if(roll.isEmpty())
                  JOptionPane.showMessageDialog(this, "Fill the Roll Number is compelsury" );
              else
              {
                    n1=FName.getText();
                    n2=MName.getText();
                    n3=LName.getText();
                    f1=FFName.getText();
                    f2=FMName.getText();
                    f3=FLName.getText();
                    if(n1.isEmpty())
                    {
                        JOptionPane.showMessageDialog(this,"Enter the Name");
                        FName.setText("");
                    }
                    else{
                    dd=(String)Date.getSelectedItem();
                    mm=(String)Month.getSelectedItem();
                    yy=(String)Year.getSelectedItem(); 
                    if(dd.isEmpty() || mm.isEmpty() || yy.isEmpty())
                    {
                        JOptionPane.showMessageDialog(this,"Please enter the correct Date");
                        Date.setSelectedIndex(0);
                        Month.setSelectedIndex(0);
                        Year.setSelectedIndex(0);
                    }
                    else{
                        int temp=0;
                    email=Email.getText();
                    if(email.isEmpty()!=true)
                    {
                        if(email.indexOf('@')>0)
                           temp=1;
                        else{
                            JOptionPane.showMessageDialog(this,"Enter Valid Email");
                            Email.setText("");
                        }
                 }if(temp==1 || email.isEmpty()==true){    
                    contact=Num.getText();
                    int flag=0;
                    if(contact.isEmpty())
                        flag=1;
                    if(contact.isEmpty()!=true || flag==1){
                    try{
                        if(flag==0)
                        {
                          for(int i=0;i<contact.length();i++)
                          {
                              int a = Integer.parseInt(String.valueOf(contact.charAt(i)));
                          }
                        }
                    try
                    {
                     String url="jdbc:mysql://localhost:3306/demo";
                     Class.forName("com.mysql.cj.jdbc.Driver");
                     Connection cn = DriverManager.getConnection(url,"root","root");
                     String name = n1+" "+n2+" "+n3;
                     String fname= f1+" "+f2+" "+f3;
                     String dob = dd+" "+mm+" "+yy;
                     String query = "INSERT INTO students(rollno,name,fathername,dob,email,contact)"
                             + "VALUES(?,?,?,?,?,?)";
                     PreparedStatement st= cn.prepareStatement(query);
                     st.setString(1,roll);
                     st.setString(2,name);
                     st.setString(3,fname);
                     st.setString(4,dob);
                     st.setString(5,email);
                     st.setString(6,contact);
                     st.executeUpdate();
                    }
                       catch(NumberFormatException e){} catch (ClassNotFoundException | SQLException ex) {
                            Logger.getLogger(Insert.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        /*AgainInsert obje=new AgainInsert();
                        obje.setVisible(true);
                        dispose();*/
                        JOptionPane.showMessageDialog(this,"Record Added Successfully!");
                        RollNo.setText("");
                        FName.setText("");
                        MName.setText("");
                        LName.setText("");
                        FFName.setText("");
                        FMName.setText("");
                        FLName.setText("");
                        Date.setSelectedIndex(0);
                        Month.setSelectedIndex(0);
                        Year.setSelectedIndex(0);
                        Email.setText("");
                        Num.setText("");
              }catch(NumberFormatException e){
                      JOptionPane.showMessageDialog(this,"Enter Valid Contact Number");
                      Num.setText("");
              }}}}}}}catch(NumberFormatException e){
              JOptionPane.showMessageDialog(this,"Enter Valid Roll Number");
              RollNo.setText("");
              } 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RollNoActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthActionPerformed

    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearActionPerformed

    private void FLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FLNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Date;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FFName;
    private javax.swing.JTextField FLName;
    private javax.swing.JTextField FMName;
    private javax.swing.JTextField FName;
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel Fname1;
    private javax.swing.JLabel Fname2;
    private javax.swing.JLabel Fname3;
    private javax.swing.JLabel Fname4;
    private javax.swing.JLabel Fname5;
    private javax.swing.JLabel Fname6;
    private javax.swing.JLabel Fname7;
    private javax.swing.JLabel Fname8;
    private javax.swing.JTextField LName;
    private javax.swing.JTextField MName;
    private javax.swing.JComboBox<String> Month;
    private javax.swing.JTextField Num;
    private javax.swing.JTextField RollNo;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
